### ISSUE TITLE
Question about "ortho_reg: loss - max_margin_loss"

### ISSUE THREAD

**Issue by mangohero1985** [ruidan/Unsupervised-Aspect-Extraction#15]
Hi Ruidan, thank you for the really excellent research and coding.
I was also really lucky to hear your presentation in ACL2017.

In the ending of each training epoch, you showed an info about "ortho_reg: loss - max_margin_loss".
I don't really understand the meaning of this. Could you please explain it? or you can show me some references about it.
Thank you so much.

**Comment by mangohero1985** [comment]
Was it from this "L(θ) = J(θ) + λU(θ) "?

**Comment by ruidan** [comment]
The ortho_reg refers to the orthogonal regularisation term described in the paper section 3.4, which is denoted by U in the overall objective loss in the above formula.
