### ISSUE TITLE
Source of data

### ISSUE THREAD

**Issue by stephantul** [ruidan/Unsupervised-Aspect-Extraction#25]
Hi @ruidan 

I was wondering where you got the beer dataset, since it does not seem to be publicly available any more. It seems to me that the beer dataset you provide already has some stopword removal applied to it. Do you know how this was done, and whether the original datasets can be found anywhere?

Kind regards,
Stéphan

**Comment by ruidan** [comment]
Hi Stéphan,

The beer dataset provided by the authors already has the stop words removed, and I did not perform any further data preprocess on this dataset. You may contact the authors to ask for the unpreprocessed dataset.

**Comment by stephantul** [comment]
Ok, thanks for the quick reply
